CREATE TABLE KATEGORI(
    KODE_KAT VARCHAR(255) PRIMARY KEY,
    NAMA_KAT VARCHAR(255) NOT NULL
);

CREATE TABLE MERK(
    KODE_MERK VARCHAR(255) PRIMARY KEY,
    NAMA_MERK VARCHAR(255) NOT NULL
);

CREATE TABLE CUSTOMER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    NAMA_CUST VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    NO_TELP VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    SALDO NUMERIC(9)
);

CREATE TABLE BARANG(
    ID int(30) PRIMARY KEY AUTO_INCREMENT,
    NAMA_BARANG VARCHAR(255) NOT NULL,
    MERK VARCHAR(255) REFERENCES MERK(KODE_MERK),
    KATEGORI VARCHAR(255) REFERENCES KATEGORI(KODE_KAT),
    STOK NUMERIC(30),
    HARGA NUMERIC(30) NOT NULL,
    IMG BLOB NOT NULL
);

CREATE TABLE H_BELI(
    NOMOR_NOTA VARCHAR(255) PRIMARY KEY,
    ID_CUSTOMER NUMERIC(30) REFERENCES CUSTOMER(ID),
    TOTAL_PEMBELIAN NUMERIC(30) NOT NULL,
    TANGGAL_PEMBELIAN DATE NOT NULL
);

CREATE TABLE D_BELI(
    NOMOR_NOTA VARCHAR(255) REFERENCES H_BELI(NOMOR_NOTA),
    ID_BARANG NUMERIC(30) REFERENCES BARANG(ID),
    JUMLAH NUMERIC(30),
    SUBTOTAL NUMERIC(30)
);

CREATE TABLE REQ_SALDO(
    ID NUMERIC(30) PRIMARY KEY,
    ID_CUST NUMERIC(30) REFERENCES CUSTOMER(ID),
    SALDOREQ NUMERIC(30)
);

CREATE TABLE GARANSI(
    KODE_MERK VARCHAR(255) REFERENCES MERK(KODE_MERK),
    DURASI NUMERIC(30)
);

CREATE TABLE DIGITAL_SELLER(
    ID_USER VARCHAR(255) REFERENCES CUSTOMER(USERNAME),
    ID_BARANG VARCHAR(255) REFERENCES BARANG(ID)
);

